version: "3"

services:
  eotdl-mongo:
    image: mongo

  eotdl-api:
    build: ./apis/eotdl
    container_name: eotdl-api
    environment:
      - MONGO_URL=mongodb://eotdl-mongo:27017
      - MONGO_DB_NAME=eotdl
    env_file: # auth0 credentials
      - .env
    volumes:
      - ./apis/eotdl:/api
      - ./lib/eotdl:/api/eotdl
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload