version: '3'
services:
  jupyter:
    build:
      context: ./tutorials
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./tutorials:/ipynbs
      - ./eotdl/eotdl:/ipynbs/eotdl
      - ~/.cache/eotdl:/root/.cache/eotdl
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''