version: "3"

services:
  eotdl-mongo-test:
    image: mongo

  eotdl-minio-test:
    image: minio/minio
    container_name: eotdl-minio-test
    environment:
      - MINIO_ROOT_USER=eotdl
      - MINIO_ROOT_PASSWORD=12345678
    command: server /data --console-address ":9001"

  eotdl-api-test:
    build: ./api
    container_name: eotdl-api-test
    environment:
      - MONGO_URL=mongodb://eotdl-mongo-test:27017
      - MONGO_DB_NAME=test
      - S3_ENDPOINT=eotdl-minio-test:9000
      - ACCESS_KEY_ID=eotdl
      - SECRET_ACCESS_KEY=12345678
      - S3_BUCKET=test
      - ADMIN_API_KEY=12345678
      - S3_SSL=False
      - TZ=Europe/Madrid
      - API_BASE_URL=http://localhost:8010 # used to generate file urls
    env_file: # auth0 and eox credentials
      - .env
    volumes:
      - ./api:/api
      - ./eotdl/eotdl:/api/api/eotdl
    command: uvicorn api.api.main:app --host 0.0.0.0 --reload

  # eotdl-test:
  #   build: ./eotdl 
  #   container_name: eotdl-test
  #   environment:
  #     - EOTDL_API_URL=http://eotdl-api-test:8000
  #   volumes:
  #     - ./eotdl:/eotdl
  #   tty: true