version: "3"

services:
  eotdl-mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  eotdl-minio:
    image: minio/minio
    container_name: eotdl-minio
    ports:
      - 9020:9000
      - 9021:9001
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=eotdl
      - MINIO_ROOT_PASSWORD=12345678
    command: server /data --console-address ":9001"

  eotdl-api:
    build: ./apis/eotdl
    container_name: eotdl-api
    # platform: linux/amd64
    environment:
      - MONGO_URL=mongodb://eotdl-mongo:27017
      - MONGO_DB_NAME=eotdl
      - S3_ENDPOINT=eotdl-minio:9000
      - ACCESS_KEY_ID=eotdl
      - SECRET_ACCESS_KEY=12345678
      - S3_BUCKET=dev
      - S3_SSL=False
      - ADMIN_API_KEY=12345678
      - TZ=Europe/Madrid
      - API_BASE_URL=http://localhost:8010 # used to generate file urls
    env_file: # auth0 and eox credentials
      - .env
    volumes:
      - ./apis/eotdl:/api
      - ./eotdl/eotdl:/api/eotdl
    ports:
      - 8010:8000
    command: uvicorn api.main:app --host 0.0.0.0 --reload
