# version: "3"

services:
  eotdl-mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db

  eotdl-minio:
    image: minio/minio
    container_name: eotdl-minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=eotdl
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_HOST=0.0.0.0
    command: server /data --console-address ":9001"
    
  eotdl-api:
    build: ./api
    # image: eotdl/api:2025.10.9
    container_name: eotdl-api
    platform: linux/amd64
    environment:
      - MONGO_URL=mongodb://eotdl-mongo:27017
      - MONGO_DB_NAME=eotdl
      - S3_ENDPOINT=192.168.0.139:9000 # use host ip to generate presigned urls (allow minio port on firewal!)
      - ACCESS_KEY_ID=eotdl
      - SECRET_ACCESS_KEY=12345678
      - S3_BUCKET=dev
      - S3_SSL=False
      - ADMIN_API_KEY=12345678
      - TZ=Europe/Madrid
      # - API_BASE_URL=http://localhost:8000 # used to generate file urls
    env_file: # auth0 and eox credentials
      - .env
    volumes:
      - ./api/api:/api
      - ./eotdl/eotdl:/api/eotdl
      - ./kk:/tmp
    ports:
      - 8000:8000
    command: uvicorn api.main:app --host 0.0.0.0 --reload