[project]
name = "eotdl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geomet>=1.1.0",
    "geopandas>=1.0.1",
    "jupyter>=1.1.1",
    "markdown>=3.7",
    "minio>=7.2.15",
    "pydantic>=2.10.6",
    "pyjwt>=2.10.1",
    "pystac>=1.12.1",
    "python-dotenv>=1.0.1",
    "python-frontmatter>=1.1.0",
    "pyyaml>=6.0.2",
    "rasterio>=1.4.3",
    "requests>=2.32.3",
    "sentinelhub>=3.11.1",
    "stac-geoparquet>=0.6.0",
    "tqdm>=4.67.1",
    "typer>=0.15.1",
]

[dependency-groups]
dev = [
    "boto3>=1.37.20",
    "pymongo>=4.11.3",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "ruff>=0.11.2",
]
